
// Generated manually and inspired by the one generated by the Nim Compiler.
// In order to see the header file generated by Nim just run `make liblibp2p`
// from the root repo folder and the header should be created in
// nimcache/release/liblibp2p/liblibp2p.h
#ifndef __liblibp2p__
#define __liblibp2p__

#include <stddef.h>
#include <stdint.h>

// The possible returned values for the functions that return int
#define RET_OK                0
#define RET_ERR               1
#define RET_MISSING_CALLBACK  2

#ifdef __cplusplus
extern "C" {
#endif

typedef void (*WakuCallBack) (int callerRet, const char* msg, size_t len, void* userData);

// Creates a new instance of the libp2p node.
// Sets up the libp2p node from the given configuration.
// Returns a pointer to the Context needed by the rest of the API functions.
void* libp2p_new(
             const char* configJson,
             WakuCallBack callback,
             void* userData);

int libp2p_start(void* ctx,
               WakuCallBack callback,
               void* userData);

int libp2p_stop(void* ctx,
              WakuCallBack callback,
              void* userData);

// Destroys an instance of a libp2p node created with libp2p_new
int libp2p_destroy(void* ctx,
                 WakuCallBack callback,
                 void* userData);

int libp2p_version(void* ctx,
                 WakuCallBack callback,
                 void* userData);

// Sets a callback that will be invoked whenever an event occurs.
// It is crucial that the passed callback is fast, non-blocking and potentially thread-safe.
void libp2p_set_event_callback(void* ctx,
                             WakuCallBack callback,
                             void* userData);

int libp2p_content_topic(void* ctx,
                       const char* appName,
                       unsigned int appVersion,
                       const char* contentTopicName,
                       const char* encoding,
                       WakuCallBack callback,
                       void* userData);

int libp2p_pubsub_topic(void* ctx,
                      const char* topicName,
                      WakuCallBack callback,
                      void* userData);

int libp2p_default_pubsub_topic(void* ctx,
                              WakuCallBack callback,
                              void* userData);

int libp2p_relay_publish(void* ctx,
                       const char* pubSubTopic,
                       const char* jsonWakuMessage,
                       unsigned int timeoutMs,
                       WakuCallBack callback,
                       void* userData);

int libp2p_lightpush_publish(void* ctx,
                       const char* pubSubTopic,
                       const char* jsonWakuMessage,
                       WakuCallBack callback,
                       void* userData);

int libp2p_relay_subscribe(void* ctx,
                         const char* pubSubTopic,
                         WakuCallBack callback,
                         void* userData);

int libp2p_relay_add_protected_shard(void* ctx,
                                   int clusterId,
                                   int shardId,
                                   char* publicKey,
                                   WakuCallBack callback,
                                   void* userData);

int libp2p_relay_unsubscribe(void* ctx,
                           const char* pubSubTopic,
                           WakuCallBack callback,
                           void* userData);

int libp2p_filter_subscribe(void* ctx,
                          const char* pubSubTopic,
                          const char* contentTopics,
                          WakuCallBack callback,
                          void* userData);

int libp2p_filter_unsubscribe(void* ctx,
                            const char* pubSubTopic,
                            const char* contentTopics,
                            WakuCallBack callback,
                            void* userData);

int libp2p_filter_unsubscribe_all(void* ctx,
                                WakuCallBack callback,
                                void* userData);

int libp2p_relay_get_num_connected_peers(void* ctx,
                           const char* pubSubTopic,
                           WakuCallBack callback,
                           void* userData);

int libp2p_relay_get_connected_peers(void* ctx,
                           const char* pubSubTopic,
                           WakuCallBack callback,
                           void* userData);

int libp2p_relay_get_num_peers_in_mesh(void* ctx,
                           const char* pubSubTopic,
                           WakuCallBack callback,
                           void* userData);

int libp2p_relay_get_peers_in_mesh(void* ctx,
                           const char* pubSubTopic,
                           WakuCallBack callback,
                           void* userData);

int libp2p_store_query(void* ctx,
                        const char* jsonQuery,
                        const char* peerAddr,
                        int timeoutMs,
                        WakuCallBack callback,
                        void* userData);

int libp2p_connect(void* ctx,
                 const char* peerMultiAddr,
                 unsigned int timeoutMs,
                 WakuCallBack callback,
                 void* userData);

int libp2p_disconnect_peer_by_id(void* ctx,
                 const char* peerId,
                 WakuCallBack callback,
                 void* userData);

int libp2p_disconnect_all_peers(void* ctx,
                 WakuCallBack callback,
                 void* userData);

int libp2p_dial_peer(void* ctx,
                 const char* peerMultiAddr,
                 const char* protocol,
                 int timeoutMs,
                 WakuCallBack callback,
                 void* userData);

int libp2p_dial_peer_by_id(void* ctx,
                 const char* peerId,
                 const char* protocol,
                 int timeoutMs,
                 WakuCallBack callback,
                 void* userData);

int libp2p_get_peerids_from_peerstore(void* ctx,
                                    WakuCallBack callback,
                                    void* userData);

int libp2p_get_connected_peers_info(void* ctx,
                                    WakuCallBack callback,
                                    void* userData);

int libp2p_get_peerids_by_protocol(void* ctx,
                                 const char* protocol,
                                 WakuCallBack callback,
                                 void* userData);

int libp2p_listen_addresses(void* ctx,
                          WakuCallBack callback,
                          void* userData);

int libp2p_get_connected_peers(void* ctx,
                          WakuCallBack callback,
                          void* userData);

// Returns a list of multiaddress given a url to a DNS discoverable ENR tree
// Parameters
//     char* entTreeUrl: URL containing a discoverable ENR tree
//     char* nameDnsServer: The nameserver to resolve the ENR tree url.
//     int timeoutMs: Timeout value in milliseconds to execute the call.
int libp2p_dns_discovery(void* ctx,
                       const char* entTreeUrl,
                       const char* nameDnsServer,
                       int timeoutMs,
                       WakuCallBack callback,
                       void* userData);

// Updates the bootnode list used for discovering new peers via DiscoveryV5
// bootnodes - JSON array containing the bootnode ENRs i.e. `["enr:...", "enr:..."]`
int libp2p_discv5_update_bootnodes(void* ctx,
                                 char* bootnodes,
                                 WakuCallBack callback,
                                 void* userData);

int libp2p_start_discv5(void* ctx,
                      WakuCallBack callback,
                      void* userData);

int libp2p_stop_discv5(void* ctx,
                     WakuCallBack callback,
                     void* userData);

// Retrieves the ENR information
int libp2p_get_my_enr(void* ctx,
                    WakuCallBack callback,
                    void* userData);

int libp2p_get_my_peerid(void* ctx,
                    WakuCallBack callback,
                    void* userData);

int libp2p_get_metrics(void* ctx,
                    WakuCallBack callback,
                    void* userData);

int libp2p_peer_exchange_request(void* ctx,
                               int numPeers,
                               WakuCallBack callback,
                               void* userData);

int libp2p_ping_peer(void* ctx,
                        const char* peerAddr,
                        int timeoutMs,
                        WakuCallBack callback,
                        void* userData);

int libp2p_is_online(void* ctx,
                        WakuCallBack callback,
                        void* userData);

#ifdef __cplusplus
}
#endif

#endif /* __liblibp2p__ */
